class TransHeadServer {
  dynamic errorMessage;
  bool isNewBill;
  int transTypeNumber;
  int transHeadNumber;
  int companyNumber;
  int yearNumber;
  int seriesTypeNumber;
  int seriesNumber;
  int transactionNumber;
  bool importTransactionNumber;
  int priceTypeNumber;
  dynamic transactionDate;
  dynamic createdDate;
  dynamic transEntryDate;
  dynamic counterCreated;
  int userNumberCreated;
  dynamic userNameCreated;
  int comLocationNumber;
  int transDiscRate;
  int transDiscAmount;
  int paymentCashAmount;
  int paymentCardAmount;
  dynamic paymentRemarks;
  int transExpensesRate;
  int transExpensesAmount;
  dynamic accHeadCodeContractor;
  dynamic accHeadNameContractor;
  int accHeadNumberContractor;
  int roundOffAmount;
  int transactionAmount;
  int savedAmount;
  int savedAmountItem;
  int stockPointNumber;
  int accHeadNumber;
  int creditDays;
  int creditLimit;
  dynamic ledgerBalancePrevious;
  int receiptCash;
  dynamic ledgerBalanceCurrent;
  int ledgerBalanceCreditDays;
  int accHeadNumberSalesman;
  int transHeadNumberRequisition;
  int accHeadNumberAgent;
  int memberNumber;
  int memberPointNumber;
  int memberTotalPoints;
  int memberBillPoints;
  int memberTypeNumber;
  int areaNumber;
  int vanNumber;
  dynamic vanName;
  dynamic transactionRemarks1;
  dynamic transactionRemarks2;
  int accountTypeNumber;
  dynamic customerName;
  dynamic contactPerson;
  int customerSeriesNumber;
  dynamic customerCode;
  dynamic customerAddress;
  dynamic customerPlace;
  dynamic customerPost;
  dynamic customerDistrict;
  dynamic deliveryAddress;
  dynamic email;
  dynamic popupMessage;
  dynamic customerPhone;
  dynamic agentCode;
  dynamic agentName;
  dynamic salesManName;
  dynamic salesManCode;
  dynamic stockPointNameFrom;
  dynamic stockPointNameTo;
  int stockPointNumberTo;
  int stockPointNumberFrom;
  dynamic stockPointName;
  dynamic memberName;
  dynamic memberCode;
  dynamic memberMobileNo;
  dynamic smsMobileNo;
  dynamic areaName;
  dynamic areaCode;
  dynamic userNameOpened;
  dynamic userNameSubmit;
  dynamic vehicleNumber;
  dynamic cstNumber;
  dynamic vatNumber;
  dynamic gstNumber;
  dynamic panNumber;
  int stateNumber;
  dynamic stateCode;
  dynamic stateName;
  dynamic licenseNumber;
  dynamic documentNumber;
  dynamic documentDate;
  dynamic documentDatePr;
  int documentAmount;
  int documentAmountDiff;
  int userNumberModified;
  dynamic counterModified;
  dynamic modifiedDate;
  int userNumberOpened;
  int userNumberSubmit;
  dynamic submitDate;
  int submitTypeNumber;
  dynamic userSubmitRemarks;
  int userHierarchy;
  bool isCancel;
  bool billEdited;
  bool updateMaster;
  bool updateItemMasterGst;
  int transactionNumberImport;
  dynamic transactionDateImport;
  int transAgentRate;
  int transAgentAmount;
  int transCommRate;
  int transCommAmount;
  int transFreightAmount;
  int transSalesTaxRate;
  int transSalesTaxAmount;
  int transCessRate;
  int transCessAmount;
  int transOtherExpense;
  int agentRate;
  int agentAmount;
  int commRate;
  int commAmount;
  int transCostAmount;
  int transSplDiscRate;
  int transSplDiscAmount;
  int transDisplayAmount;
  int itemTotalAmount;
  int transactionCost;
  int transactionPostingAmount;
  int itemTotalGrossAmount;
  int itemTotalDiscount;
  int itemTotalExtraDiscount;
  int itemTotalNetAmount;
  int itemTotalTaxAmount;
  int transExtraTotal;
  bool includeTaxInPrice;
  dynamic currencySymbol;
  int luxuryItemGroupNumber;
  int luxuryGstRate;
  int luxuryPriceTypeNumber;
  bool isLuxury;
  int tenderCash;
  int accountTypeNumberPayment;
  int accHeadNumberPayment;
  int accHeadNumberAdvance;
  int advanceAmount;
  int balanceCash;
  bool isLocked;
  int currencyDecimals;
  bool allowManualBillNo;
  int itemQuantityTotal;
  int itemSaleQuantityTotal;
  int discountQuantityTotal;
  int itemTotalQuantityTotal;
  int itemNetUnitPriceTotal;
  int specialDiscAmountTotal;
  int itemTaxAmountTotal;
  int itemGstAmountTotal;
  int itemSgstAmountTotal;
  int itemCgstAmountTotal;
  int itemIgstAmountTotal;
  int itemGstCessAmountTotal;
  int itemCessAmountTotal;
  int transDiscAmountTotal;
  int itemCostPriceTotal;
  int itemAgentAmountTotal;
  int itemAgentAmountAfterNetAmountTotal;
  dynamic marginRateTotal;
  int itemCommissionAmountTotal;
  int itemOtherExpenseAmountTotal;
  int itemExpenseAmountTotal;
  int packingExpenseTotal;
  int itemExtraDiscountAmountTotal;
  int itemSalesPriceProfitTotal;
  int itemSalesPrice1ProfitTotal;
  int itemSalesPrice2ProfitTotal;
  int itemSalesPrice3ProfitTotal;
  int itemSalesPrice4ProfitTotal;
  int itemSalesPrice5ProfitTotal;
  int itemHandlingChargesTotal;
  int schemeNumber;
  dynamic issueNumber;
  int consumptionAmount;
  dynamic seriesTypeName;
  int schemeItemAmountTotal;
  dynamic transSchemeDiscountString;
  int transSchemeDiscount;
  int costCentreNumber;
  dynamic transactionDueDate;
  dynamic transactionDueDateString;
  int printCopyName;
  int packingSlipNo;
  int groupTypeNumber1;
  int groupTypeNumber2;
  int groupTypeNumber3;
  int itemGroupNumber1;
  int itemGroupNumber2;
  int itemGroupNumber3;
  int zeroQuantityItem;
  int cashForward;
  int previousBillCashForward;
  dynamic userName;
  int jollySilksPoints;
  int jollySilksAmount;
  int joyMartPoints;
  int joyMartAmount;
  dynamic seriesName;
  int currencyNumber;
  int currencyRate;
  dynamic accHeadName;
  int accHeadStatus;
  dynamic memPassword;
  int districtNumber;
  dynamic deliveryDate;
  bool transPrintStatus;
  dynamic companyWiseMemberPoint;
  int itemUnitPriceCurrency;
  int transCostAmount1;
  dynamic transCostAmount1String;
  int transCostAmount2;
  dynamic transCostAmount2String;
  int transCostAmount3;
  dynamic transCostAmount3String;
  dynamic itemPrefix;
  int itemGroupNumber;
  int itemGroup;
  int categoryGroup;
  int sizeGroup;
  int colorGroup;
  int currencyTotal;
  bool calculationOnSqrMeter;
  int netAmountTotal;
  int gstTotal;
  int igstTotal;
  int cgstTotal;
  int sgstTotal;
  int totalItemHandlingCharge;
  int schemDisAfterTax;
  int schemDisBeforeTax;
  int transFreightServiceItemNumber;
  dynamic transFreightServiceItemCode;
  dynamic transFreightServiceItemName;
  int transFreightAmountTaxable;
  int serviceItemGstRate;
  int serviceItemNumber2;
  dynamic serviceItemCode2;
  dynamic serviceItemName2;
  int transExpensesAmountTaxable;
  int serviceItemGstRate2;
  int serviceItemNumber3;
  dynamic serviceItemCode3;
  dynamic serviceItemName3;
  int transDisplayAmountTaxable;
  int serviceItemGstRate3;
  int transFreightCgstRate;
  int transFreightCgstAmount;
  int transFreightSgstRate;
  int transFreightSgstAmount;
  int transFreightIgstRate;
  int transFreightIgstAmount;
  int transExpensesCgstRate;
  int transExpensesCgstAmount;
  int transExpensesSgstRate;
  int transExpensesSgstAmount;
  int transExpensesIgstRate;
  int transExpensesIgstAmount;
  int transDisplayCgstRate;
  int transDisplayCgstAmount;
  int transDisplaySgstRate;
  int transDisplaySgstAmount;
  int transDisplayIgstRate;
  int transDisplayIgstAmount;
  bool is90DaysBefore;
  int profitRate;
  int profitAmount;
  int transItemCostPriceTotal;
  bool gstEnabled;
  int gstCategory;
  dynamic currencyName;
  int transCurrencyRate;
  int transCurrencyAmount;
  bool blnCalcSalesPrice;
  int supplierNumber;
  dynamic supplierCode;
  dynamic supplierName;
  dynamic mobileWhatsApp;
  dynamic companyRemarks;
  int transFreightGstRate;
  int transExpensesGstRate;
  int transExpensesServiceItemNumber;
  int transDisplayGstRate;
  int transDisplayServiceItemNumber;
  dynamic documentDateString;
  dynamic customerCity;
  dynamic customerLocation;
  dynamic customerPincode;
  int billDiscountCouponRate;
  int billDiscountCouponAmount;
  int discCouponDefinitionNumber;
  int billDiscountCouponNumber;
  int billDiscountCouponExpiryDays;
  int discountCouponNumber;
  int tcsRate;
  int tcsAmount;
  int tcsTaxableAmount;
  dynamic paymentlList;
  dynamic detailList;

  TransHeadServer({
    required this.errorMessage,
    required this.isNewBill,
    required this.transTypeNumber,
    required this.transHeadNumber,
    required this.companyNumber,
    required this.yearNumber,
    required this.seriesTypeNumber,
    required this.seriesNumber,
    required this.transactionNumber,
    required this.importTransactionNumber,
    required this.priceTypeNumber,
    required this.transactionDate,
    required this.createdDate,
    required this.transEntryDate,
    required this.counterCreated,
    required this.userNumberCreated,
    required this.userNameCreated,
    required this.comLocationNumber,
    required this.transDiscRate,
    required this.transDiscAmount,
    required this.paymentCashAmount,
    required this.paymentCardAmount,
    required this.paymentRemarks,
    required this.transExpensesRate,
    required this.transExpensesAmount,
    required this.accHeadCodeContractor,
    required this.accHeadNameContractor,
    required this.accHeadNumberContractor,
    required this.roundOffAmount,
    required this.transactionAmount,
    required this.savedAmount,
    required this.savedAmountItem,
    required this.stockPointNumber,
    required this.accHeadNumber,
    required this.creditDays,
    required this.creditLimit,
    required this.ledgerBalancePrevious,
    required this.receiptCash,
    required this.ledgerBalanceCurrent,
    required this.ledgerBalanceCreditDays,
    required this.accHeadNumberSalesman,
    required this.transHeadNumberRequisition,
    required this.accHeadNumberAgent,
    required this.memberNumber,
    required this.memberPointNumber,
    required this.memberTotalPoints,
    required this.memberBillPoints,
    required this.memberTypeNumber,
    required this.areaNumber,
    required this.vanNumber,
    required this.vanName,
    required this.transactionRemarks1,
    required this.transactionRemarks2,
    required this.accountTypeNumber,
    required this.customerName,
    required this.contactPerson,
    required this.customerSeriesNumber,
    required this.customerCode,
    required this.customerAddress,
    required this.customerPlace,
    required this.customerPost,
    required this.customerDistrict,
    required this.deliveryAddress,
    required this.email,
    required this.popupMessage,
    required this.customerPhone,
    required this.agentCode,
    required this.agentName,
    required this.salesManName,
    required this.salesManCode,
    required this.stockPointNameFrom,
    required this.stockPointNameTo,
    required this.stockPointNumberTo,
    required this.stockPointNumberFrom,
    required this.stockPointName,
    required this.memberName,
    required this.memberCode,
    required this.memberMobileNo,
    required this.smsMobileNo,
    required this.areaName,
    required this.areaCode,
    required this.userNameOpened,
    required this.userNameSubmit,
    required this.vehicleNumber,
    required this.cstNumber,
    required this.vatNumber,
    required this.gstNumber,
    required this.panNumber,
    required this.stateNumber,
    required this.stateCode,
    required this.stateName,
    required this.licenseNumber,
    required this.documentNumber,
    required this.documentDate,
    required this.documentDatePr,
    required this.documentAmount,
    required this.documentAmountDiff,
    required this.userNumberModified,
    required this.counterModified,
    required this.modifiedDate,
    required this.userNumberOpened,
    required this.userNumberSubmit,
    required this.submitDate,
    required this.submitTypeNumber,
    required this.userSubmitRemarks,
    required this.userHierarchy,
    required this.isCancel,
    required this.billEdited,
    required this.updateMaster,
    required this.updateItemMasterGst,
    required this.transactionNumberImport,
    required this.transactionDateImport,
    required this.transAgentRate,
    required this.transAgentAmount,
    required this.transCommRate,
    required this.transCommAmount,
    required this.transFreightAmount,
    required this.transSalesTaxRate,
    required this.transSalesTaxAmount,
    required this.transCessRate,
    required this.transCessAmount,
    required this.transOtherExpense,
    required this.agentRate,
    required this.agentAmount,
    required this.commRate,
    required this.commAmount,
    required this.transCostAmount,
    required this.transSplDiscRate,
    required this.transSplDiscAmount,
    required this.transDisplayAmount,
    required this.itemTotalAmount,
    required this.transactionCost,
    required this.transactionPostingAmount,
    required this.itemTotalGrossAmount,
    required this.itemTotalDiscount,
    required this.itemTotalExtraDiscount,
    required this.itemTotalNetAmount,
    required this.itemTotalTaxAmount,
    required this.transExtraTotal,
    required this.includeTaxInPrice,
    required this.currencySymbol,
    required this.luxuryItemGroupNumber,
    required this.luxuryGstRate,
    required this.luxuryPriceTypeNumber,
    required this.isLuxury,
    required this.tenderCash,
    required this.accountTypeNumberPayment,
    required this.accHeadNumberPayment,
    required this.accHeadNumberAdvance,
    required this.advanceAmount,
    required this.balanceCash,
    required this.isLocked,
    required this.currencyDecimals,
    required this.allowManualBillNo,
    required this.itemQuantityTotal,
    required this.itemSaleQuantityTotal,
    required this.discountQuantityTotal,
    required this.itemTotalQuantityTotal,
    required this.itemNetUnitPriceTotal,
    required this.specialDiscAmountTotal,
    required this.itemTaxAmountTotal,
    required this.itemGstAmountTotal,
    required this.itemSgstAmountTotal,
    required this.itemCgstAmountTotal,
    required this.itemIgstAmountTotal,
    required this.itemGstCessAmountTotal,
    required this.itemCessAmountTotal,
    required this.transDiscAmountTotal,
    required this.itemCostPriceTotal,
    required this.itemAgentAmountTotal,
    required this.itemAgentAmountAfterNetAmountTotal,
    required this.marginRateTotal,
    required this.itemCommissionAmountTotal,
    required this.itemOtherExpenseAmountTotal,
    required this.itemExpenseAmountTotal,
    required this.packingExpenseTotal,
    required this.itemExtraDiscountAmountTotal,
    required this.itemSalesPriceProfitTotal,
    required this.itemSalesPrice1ProfitTotal,
    required this.itemSalesPrice2ProfitTotal,
    required this.itemSalesPrice3ProfitTotal,
    required this.itemSalesPrice4ProfitTotal,
    required this.itemSalesPrice5ProfitTotal,
    required this.itemHandlingChargesTotal,
    required this.schemeNumber,
    required this.issueNumber,
    required this.consumptionAmount,
    required this.seriesTypeName,
    required this.schemeItemAmountTotal,
    required this.transSchemeDiscountString,
    required this.transSchemeDiscount,
    required this.costCentreNumber,
    required this.transactionDueDate,
    required this.transactionDueDateString,
    required this.printCopyName,
    required this.packingSlipNo,
    required this.groupTypeNumber1,
    required this.groupTypeNumber2,
    required this.groupTypeNumber3,
    required this.itemGroupNumber1,
    required this.itemGroupNumber2,
    required this.itemGroupNumber3,
    required this.zeroQuantityItem,
    required this.cashForward,
    required this.previousBillCashForward,
    required this.userName,
    required this.jollySilksPoints,
    required this.jollySilksAmount,
    required this.joyMartPoints,
    required this.joyMartAmount,
    required this.seriesName,
    required this.currencyNumber,
    required this.currencyRate,
    required this.accHeadName,
    required this.accHeadStatus,
    required this.memPassword,
    required this.districtNumber,
    required this.deliveryDate,
    required this.transPrintStatus,
    required this.companyWiseMemberPoint,
    required this.itemUnitPriceCurrency,
    required this.transCostAmount1,
    required this.transCostAmount1String,
    required this.transCostAmount2,
    required this.transCostAmount2String,
    required this.transCostAmount3,
    required this.transCostAmount3String,
    required this.itemPrefix,
    required this.itemGroupNumber,
    required this.itemGroup,
    required this.categoryGroup,
    required this.sizeGroup,
    required this.colorGroup,
    required this.currencyTotal,
    required this.calculationOnSqrMeter,
    required this.netAmountTotal,
    required this.gstTotal,
    required this.igstTotal,
    required this.cgstTotal,
    required this.sgstTotal,
    required this.totalItemHandlingCharge,
    required this.schemDisAfterTax,
    required this.schemDisBeforeTax,
    required this.transFreightServiceItemNumber,
    required this.transFreightServiceItemCode,
    required this.transFreightServiceItemName,
    required this.transFreightAmountTaxable,
    required this.serviceItemGstRate,
    required this.serviceItemNumber2,
    required this.serviceItemCode2,
    required this.serviceItemName2,
    required this.transExpensesAmountTaxable,
    required this.serviceItemGstRate2,
    required this.serviceItemNumber3,
    required this.serviceItemCode3,
    required this.serviceItemName3,
    required this.transDisplayAmountTaxable,
    required this.serviceItemGstRate3,
    required this.transFreightCgstRate,
    required this.transFreightCgstAmount,
    required this.transFreightSgstRate,
    required this.transFreightSgstAmount,
    required this.transFreightIgstRate,
    required this.transFreightIgstAmount,
    required this.transExpensesCgstRate,
    required this.transExpensesCgstAmount,
    required this.transExpensesSgstRate,
    required this.transExpensesSgstAmount,
    required this.transExpensesIgstRate,
    required this.transExpensesIgstAmount,
    required this.transDisplayCgstRate,
    required this.transDisplayCgstAmount,
    required this.transDisplaySgstRate,
    required this.transDisplaySgstAmount,
    required this.transDisplayIgstRate,
    required this.transDisplayIgstAmount,
    required this.is90DaysBefore,
    required this.profitRate,
    required this.profitAmount,
    required this.transItemCostPriceTotal,
    required this.gstEnabled,
    required this.gstCategory,
    required this.currencyName,
    required this.transCurrencyRate,
    required this.transCurrencyAmount,
    required this.blnCalcSalesPrice,
    required this.supplierNumber,
    required this.supplierCode,
    required this.supplierName,
    required this.mobileWhatsApp,
    required this.companyRemarks,
    required this.transFreightGstRate,
    required this.transExpensesGstRate,
    required this.transExpensesServiceItemNumber,
    required this.transDisplayGstRate,
    required this.transDisplayServiceItemNumber,
    required this.documentDateString,
    required this.customerCity,
    required this.customerLocation,
    required this.customerPincode,
    required this.billDiscountCouponRate,
    required this.billDiscountCouponAmount,
    required this.discCouponDefinitionNumber,
    required this.billDiscountCouponNumber,
    required this.billDiscountCouponExpiryDays,
    required this.discountCouponNumber,
    required this.tcsRate,
    required this.tcsAmount,
    required this.tcsTaxableAmount,
    required this.paymentlList,
    required this.detailList,
  });

  factory TransHeadServer.fromJson(Map<String, dynamic> json) =>
      TransHeadServer(
        errorMessage: json["ErrorMessage"],
        isNewBill: json["ISNewBill"],
        transTypeNumber: json["TransTypeNumber"],
        transHeadNumber: json["TransHeadNumber"],
        companyNumber: json["CompanyNumber"],
        yearNumber: json["YearNumber"],
        seriesTypeNumber: json["SeriesTypeNumber"],
        seriesNumber: json["SeriesNumber"],
        transactionNumber: json["TransactionNumber"],
        importTransactionNumber: json["ImportTransactionNumber"],
        priceTypeNumber: json["PriceTypeNumber"],
        transactionDate: json["TransactionDate"],
        createdDate: json["CreatedDate"],
        transEntryDate: json["TransEntryDate"],
        counterCreated: json["CounterCreated"],
        userNumberCreated: json["UserNumberCreated"],
        userNameCreated: json["UserNameCreated"],
        comLocationNumber: json["ComLocationNumber"],
        transDiscRate: json["TransDiscRate"],
        transDiscAmount: json["TransDiscAmount"],
        paymentCashAmount: json["PaymentCashAmount"],
        paymentCardAmount: json["PaymentCardAmount"],
        paymentRemarks: json["PaymentRemarks"],
        transExpensesRate: json["TransExpensesRate"],
        transExpensesAmount: json["TransExpensesAmount"],
        accHeadCodeContractor: json["AccHeadCodeContractor"],
        accHeadNameContractor: json["AccHeadNameContractor"],
        accHeadNumberContractor: json["AccHeadNumberContractor"],
        roundOffAmount: json["RoundOffAmount"],
        transactionAmount: json["TransactionAmount"],
        savedAmount: json["SavedAmount"],
        savedAmountItem: json["SavedAmountItem"],
        stockPointNumber: json["StockPointNumber"],
        accHeadNumber: json["AccHeadNumber"],
        creditDays: json["CreditDays"],
        creditLimit: json["CreditLimit"],
        ledgerBalancePrevious: json["LedgerBalancePrevious"],
        receiptCash: json["ReceiptCash"],
        ledgerBalanceCurrent: json["LedgerBalanceCurrent"],
        ledgerBalanceCreditDays: json["LedgerBalanceCreditDays"],
        accHeadNumberSalesman: json["AccHeadNumberSalesman"],
        transHeadNumberRequisition: json["TransHeadNumberRequisition"],
        accHeadNumberAgent: json["AccHeadNumberAgent"],
        memberNumber: json["MemberNumber"],
        memberPointNumber: json["MemberPointNumber"],
        memberTotalPoints: json["MemberTotalPoints"],
        memberBillPoints: json["MemberBillPoints"],
        memberTypeNumber: json["MemberTypeNumber"],
        areaNumber: json["AreaNumber"],
        vanNumber: json["VanNumber"],
        vanName: json["VanName"],
        transactionRemarks1: json["TransactionRemarks1"],
        transactionRemarks2: json["TransactionRemarks2"],
        accountTypeNumber: json["AccountTypeNumber"],
        customerName: json["CustomerName"],
        contactPerson: json["ContactPerson"],
        customerSeriesNumber: json["CustomerSeriesNumber"],
        customerCode: json["CustomerCode"],
        customerAddress: json["CustomerAddress"],
        customerPlace: json["CustomerPlace"],
        customerPost: json["CustomerPost"],
        customerDistrict: json["CustomerDistrict"],
        deliveryAddress: json["DeliveryAddress"],
        email: json["Email"],
        popupMessage: json["PopupMessage"],
        customerPhone: json["CustomerPhone"],
        agentCode: json["AgentCode"],
        agentName: json["AgentName"],
        salesManName: json["SalesManName"],
        salesManCode: json["SalesManCode"],
        stockPointNameFrom: json["StockPointNameFrom"],
        stockPointNameTo: json["StockPointNameTo"],
        stockPointNumberTo: json["StockPointNumberTo"],
        stockPointNumberFrom: json["StockPointNumberFrom"],
        stockPointName: json["StockPointName"],
        memberName: json["MemberName"],
        memberCode: json["MemberCode"],
        memberMobileNo: json["MemberMobileNo"],
        smsMobileNo: json["SMSMobileNo"],
        areaName: json["AreaName"],
        areaCode: json["AreaCode"],
        userNameOpened: json["UserNameOpened"],
        userNameSubmit: json["UserNameSubmit"],
        vehicleNumber: json["VehicleNumber"],
        cstNumber: json["CSTNumber"],
        vatNumber: json["VATNumber"],
        gstNumber: json["GSTNumber"],
        panNumber: json["PANNumber"],
        stateNumber: json["StateNumber"],
        stateCode: json["StateCode"],
        stateName: json["StateName"],
        licenseNumber: json["LicenseNumber"],
        documentNumber: json["DocumentNumber"],
        documentDate: json["DocumentDate"],
        documentDatePr: json["DocumentDatePR"],
        documentAmount: json["DocumentAmount"],
        documentAmountDiff: json["DocumentAmountDiff"],
        userNumberModified: json["UserNumberModified"],
        counterModified: json["CounterModified"],
        modifiedDate: json["ModifiedDate"],
        userNumberOpened: json["UserNumberOpened"],
        userNumberSubmit: json["UserNumberSubmit"],
        submitDate: json["SubmitDate"],
        submitTypeNumber: json["SubmitTypeNumber"],
        userSubmitRemarks: json["UserSubmitRemarks"],
        userHierarchy: json["UserHierarchy"],
        isCancel: json["IsCancel"],
        billEdited: json["BillEdited"],
        updateMaster: json["UpdateMaster"],
        updateItemMasterGst: json["UpdateItemMasterGST"],
        transactionNumberImport: json["TransactionNumberImport"],
        transactionDateImport: json["TransactionDateImport"],
        transAgentRate: json["TransAgentRate"],
        transAgentAmount: json["TransAgentAmount"],
        transCommRate: json["TransCommRate"],
        transCommAmount: json["TransCommAmount"],
        transFreightAmount: json["TransFreightAmount"],
        transSalesTaxRate: json["TransSalesTaxRate"],
        transSalesTaxAmount: json["TransSalesTaxAmount"],
        transCessRate: json["TransCessRate"],
        transCessAmount: json["TransCessAmount"],
        transOtherExpense: json["TransOtherExpense"],
        agentRate: json["AgentRate"],
        agentAmount: json["AgentAmount"],
        commRate: json["CommRate"],
        commAmount: json["CommAmount"],
        transCostAmount: json["TransCostAmount"],
        transSplDiscRate: json["TransSplDiscRate"],
        transSplDiscAmount: json["TransSplDiscAmount"],
        transDisplayAmount: json["TransDisplayAmount"],
        itemTotalAmount: json["ItemTotalAmount"],
        transactionCost: json["TransactionCost"],
        transactionPostingAmount: json["TransactionPostingAmount"],
        itemTotalGrossAmount: json["ItemTotalGrossAmount"],
        itemTotalDiscount: json["ItemTotalDiscount"],
        itemTotalExtraDiscount: json["ItemTotalExtraDiscount"],
        itemTotalNetAmount: json["ItemTotalNetAmount"],
        itemTotalTaxAmount: json["ItemTotalTaxAmount"],
        transExtraTotal: json["TransExtraTotal"],
        includeTaxInPrice: json["IncludeTaxInPrice"],
        currencySymbol: json["CurrencySymbol"],
        luxuryItemGroupNumber: json["LuxuryItemGroupNumber"],
        luxuryGstRate: json["LuxuryGSTRate"],
        luxuryPriceTypeNumber: json["LuxuryPriceTypeNumber"],
        isLuxury: json["IsLuxury"],
        tenderCash: json["TenderCash"],
        accountTypeNumberPayment: json["AccountTypeNumberPayment"],
        accHeadNumberPayment: json["AccHeadNumberPayment"],
        accHeadNumberAdvance: json["AccHeadNumberAdvance"],
        advanceAmount: json["AdvanceAmount"],
        balanceCash: json["BalanceCash"],
        isLocked: json["IsLocked"],
        currencyDecimals: json["CurrencyDecimals"],
        allowManualBillNo: json["AllowManualBillNo"],
        itemQuantityTotal: json["ItemQuantityTotal"],
        itemSaleQuantityTotal: json["ItemSaleQuantityTotal"],
        discountQuantityTotal: json["DiscountQuantityTotal"],
        itemTotalQuantityTotal: json["ItemTotalQuantityTotal"],
        itemNetUnitPriceTotal: json["ItemNetUnitPriceTotal"],
        specialDiscAmountTotal: json["SpecialDiscAmountTotal"],
        itemTaxAmountTotal: json["ItemTaxAmountTotal"],
        itemGstAmountTotal: json["ItemGSTAmountTotal"],
        itemSgstAmountTotal: json["ItemSGSTAmountTotal"],
        itemCgstAmountTotal: json["ItemCGSTAmountTotal"],
        itemIgstAmountTotal: json["ItemIGSTAmountTotal"],
        itemGstCessAmountTotal: json["ItemGSTCessAmountTotal"],
        itemCessAmountTotal: json["ItemCessAmountTotal"],
        transDiscAmountTotal: json["TransDiscAmountTotal"],
        itemCostPriceTotal: json["ItemCostPriceTotal"],
        itemAgentAmountTotal: json["ItemAgentAmountTotal"],
        itemAgentAmountAfterNetAmountTotal:
            json["ItemAgentAmountAfterNetAmountTotal"],
        marginRateTotal: json["MarginRateTotal"],
        itemCommissionAmountTotal: json["ItemCommissionAmountTotal"],
        itemOtherExpenseAmountTotal: json["ItemOtherExpenseAmountTotal"],
        itemExpenseAmountTotal: json["ItemExpenseAmountTotal"],
        packingExpenseTotal: json["PackingExpenseTotal"],
        itemExtraDiscountAmountTotal: json["ItemExtraDiscountAmountTotal"],
        itemSalesPriceProfitTotal: json["ItemSalesPriceProfitTotal"],
        itemSalesPrice1ProfitTotal: json["ItemSalesPrice1ProfitTotal"],
        itemSalesPrice2ProfitTotal: json["ItemSalesPrice2ProfitTotal"],
        itemSalesPrice3ProfitTotal: json["ItemSalesPrice3ProfitTotal"],
        itemSalesPrice4ProfitTotal: json["ItemSalesPrice4ProfitTotal"],
        itemSalesPrice5ProfitTotal: json["ItemSalesPrice5ProfitTotal"],
        itemHandlingChargesTotal: json["ItemHandlingChargesTotal"],
        schemeNumber: json["SchemeNumber"],
        issueNumber: json["IssueNumber"],
        consumptionAmount: json["ConsumptionAmount"],
        seriesTypeName: json["SeriesTypeName"],
        schemeItemAmountTotal: json["SchemeItemAmountTotal"],
        transSchemeDiscountString: json["TransSchemeDiscountString"],
        transSchemeDiscount: json["TransSchemeDiscount"],
        costCentreNumber: json["CostCentreNumber"],
        transactionDueDate: json["TransactionDueDate"],
        transactionDueDateString: json["TransactionDueDateString"],
        printCopyName: json["PrintCopyName"],
        packingSlipNo: json["PackingSlipNo"],
        groupTypeNumber1: json["GroupTypeNumber1"],
        groupTypeNumber2: json["GroupTypeNumber2"],
        groupTypeNumber3: json["GroupTypeNumber3"],
        itemGroupNumber1: json["ItemGroupNumber1"],
        itemGroupNumber2: json["ItemGroupNumber2"],
        itemGroupNumber3: json["ItemGroupNumber3"],
        zeroQuantityItem: json["ZeroQuantityItem"],
        cashForward: json["CashForward"],
        previousBillCashForward: json["PreviousBillCashForward"],
        userName: json["UserName"],
        jollySilksPoints: json["JollySilksPoints"],
        jollySilksAmount: json["JollySilksAmount"],
        joyMartPoints: json["JoyMartPoints"],
        joyMartAmount: json["JoyMartAmount"],
        seriesName: json["SeriesName"],
        currencyNumber: json["CurrencyNumber"],
        currencyRate: json["CurrencyRate"],
        accHeadName: json["AccHeadName"],
        accHeadStatus: json["AccHeadStatus"],
        memPassword: json["MemPassword"],
        districtNumber: json["DistrictNumber"],
        deliveryDate: json["DeliveryDate"],
        transPrintStatus: json["TransPrintStatus"],
        companyWiseMemberPoint: json["CompanyWiseMemberPoint"],
        itemUnitPriceCurrency: json["ItemUnitPriceCurrency"],
        transCostAmount1: json["TransCostAmount1"],
        transCostAmount1String: json["TransCostAmount1string"],
        transCostAmount2: json["TransCostAmount2"],
        transCostAmount2String: json["TransCostAmount2string"],
        transCostAmount3: json["TransCostAmount3"],
        transCostAmount3String: json["TransCostAmount3string"],
        itemPrefix: json["ItemPrefix"],
        itemGroupNumber: json["ItemGroupNumber"],
        itemGroup: json["ItemGroup"],
        categoryGroup: json["CategoryGroup"],
        sizeGroup: json["SizeGroup"],
        colorGroup: json["ColorGroup"],
        currencyTotal: json["CurrencyTotal"],
        calculationOnSqrMeter: json["CalculationOnSqrMeter"],
        netAmountTotal: json["NetAmountTotal"],
        gstTotal: json["GSTTotal"],
        igstTotal: json["IGSTTotal"],
        cgstTotal: json["CGSTTotal"],
        sgstTotal: json["SGSTTotal"],
        totalItemHandlingCharge: json["TotalItemHandlingCharge"],
        schemDisAfterTax: json["SchemDisAfterTax"],
        schemDisBeforeTax: json["SchemDisBeforeTax"],
        transFreightServiceItemNumber: json["TransFreightServiceItemNumber"],
        transFreightServiceItemCode: json["TransFreightServiceItemCode"],
        transFreightServiceItemName: json["TransFreightServiceItemName"],
        transFreightAmountTaxable: json["TransFreightAmountTaxable"],
        serviceItemGstRate: json["ServiceItemGSTRate"],
        serviceItemNumber2: json["ServiceItemNumber2"],
        serviceItemCode2: json["ServiceItemCode2"],
        serviceItemName2: json["ServiceItemName2"],
        transExpensesAmountTaxable: json["TransExpensesAmountTaxable"],
        serviceItemGstRate2: json["ServiceItemGSTRate2"],
        serviceItemNumber3: json["ServiceItemNumber3"],
        serviceItemCode3: json["ServiceItemCode3"],
        serviceItemName3: json["ServiceItemName3"],
        transDisplayAmountTaxable: json["TransDisplayAmountTaxable"],
        serviceItemGstRate3: json["ServiceItemGSTRate3"],
        transFreightCgstRate: json["TransFreightCGSTRate"],
        transFreightCgstAmount: json["TransFreightCGSTAmount"],
        transFreightSgstRate: json["TransFreightSGSTRate"],
        transFreightSgstAmount: json["TransFreightSGSTAmount"],
        transFreightIgstRate: json["TransFreightIGSTRate"],
        transFreightIgstAmount: json["TransFreightIGSTAmount"],
        transExpensesCgstRate: json["TransExpensesCGSTRate"],
        transExpensesCgstAmount: json["TransExpensesCGSTAmount"],
        transExpensesSgstRate: json["TransExpensesSGSTRate"],
        transExpensesSgstAmount: json["TransExpensesSGSTAmount"],
        transExpensesIgstRate: json["TransExpensesIGSTRate"],
        transExpensesIgstAmount: json["TransExpensesIGSTAmount"],
        transDisplayCgstRate: json["TransDisplayCGSTRate"],
        transDisplayCgstAmount: json["TransDisplayCGSTAmount"],
        transDisplaySgstRate: json["TransDisplaySGSTRate"],
        transDisplaySgstAmount: json["TransDisplaySGSTAmount"],
        transDisplayIgstRate: json["TransDisplayIGSTRate"],
        transDisplayIgstAmount: json["TransDisplayIGSTAmount"],
        is90DaysBefore: json["Is90DaysBefore"],
        profitRate: json["ProfitRate"],
        profitAmount: json["ProfitAmount"],
        transItemCostPriceTotal: json["TransItemCostPriceTotal"],
        gstEnabled: json["GSTEnabled"],
        gstCategory: json["GSTCategory"],
        currencyName: json["CurrencyName"],
        transCurrencyRate: json["TransCurrencyRate"],
        transCurrencyAmount: json["TransCurrencyAmount"],
        blnCalcSalesPrice: json["blnCalcSalesPrice"],
        supplierNumber: json["SupplierNumber"],
        supplierCode: json["SupplierCode"],
        supplierName: json["SupplierName"],
        mobileWhatsApp: json["MobileWhatsApp"],
        companyRemarks: json["CompanyRemarks"],
        transFreightGstRate: json["TransFreightGSTRate"],
        transExpensesGstRate: json["TransExpensesGSTRate"],
        transExpensesServiceItemNumber: json["TransExpensesServiceItemNumber"],
        transDisplayGstRate: json["TransDisplayGSTRate"],
        transDisplayServiceItemNumber: json["TransDisplayServiceItemNumber"],
        documentDateString: json["DocumentDateString"],
        customerCity: json["CustomerCity"],
        customerLocation: json["CustomerLocation"],
        customerPincode: json["CustomerPincode"],
        billDiscountCouponRate: json["BillDiscountCouponRate"],
        billDiscountCouponAmount: json["BillDiscountCouponAmount"],
        discCouponDefinitionNumber: json["DiscCouponDefinitionNumber"],
        billDiscountCouponNumber: json["BillDiscountCouponNumber"],
        billDiscountCouponExpiryDays: json["BillDiscountCouponExpiryDays"],
        discountCouponNumber: json["DiscountCouponNumber"],
        tcsRate: json["TCSRate"],
        tcsAmount: json["TCSAmount"],
        tcsTaxableAmount: json["TCSTaxableAmount"],
        paymentlList: json["PaymentlList"],
        detailList: json["DetailList"],
      );

  Map<String, dynamic> toJson() => {
        "ErrorMessage": errorMessage,
        "ISNewBill": isNewBill,
        "TransTypeNumber": transTypeNumber,
        "TransHeadNumber": transHeadNumber,
        "CompanyNumber": companyNumber,
        "YearNumber": yearNumber,
        "SeriesTypeNumber": seriesTypeNumber,
        "SeriesNumber": seriesNumber,
        "TransactionNumber": transactionNumber,
        "ImportTransactionNumber": importTransactionNumber,
        "PriceTypeNumber": priceTypeNumber,
        "TransactionDate": transactionDate,
        "CreatedDate": createdDate,
        "TransEntryDate": transEntryDate,
        "CounterCreated": counterCreated,
        "UserNumberCreated": userNumberCreated,
        "UserNameCreated": userNameCreated,
        "ComLocationNumber": comLocationNumber,
        "TransDiscRate": transDiscRate,
        "TransDiscAmount": transDiscAmount,
        "PaymentCashAmount": paymentCashAmount,
        "PaymentCardAmount": paymentCardAmount,
        "PaymentRemarks": paymentRemarks,
        "TransExpensesRate": transExpensesRate,
        "TransExpensesAmount": transExpensesAmount,
        "AccHeadCodeContractor": accHeadCodeContractor,
        "AccHeadNameContractor": accHeadNameContractor,
        "AccHeadNumberContractor": accHeadNumberContractor,
        "RoundOffAmount": roundOffAmount,
        "TransactionAmount": transactionAmount,
        "SavedAmount": savedAmount,
        "SavedAmountItem": savedAmountItem,
        "StockPointNumber": stockPointNumber,
        "AccHeadNumber": accHeadNumber,
        "CreditDays": creditDays,
        "CreditLimit": creditLimit,
        "LedgerBalancePrevious": ledgerBalancePrevious,
        "ReceiptCash": receiptCash,
        "LedgerBalanceCurrent": ledgerBalanceCurrent,
        "LedgerBalanceCreditDays": ledgerBalanceCreditDays,
        "AccHeadNumberSalesman": accHeadNumberSalesman,
        "TransHeadNumberRequisition": transHeadNumberRequisition,
        "AccHeadNumberAgent": accHeadNumberAgent,
        "MemberNumber": memberNumber,
        "MemberPointNumber": memberPointNumber,
        "MemberTotalPoints": memberTotalPoints,
        "MemberBillPoints": memberBillPoints,
        "MemberTypeNumber": memberTypeNumber,
        "AreaNumber": areaNumber,
        "VanNumber": vanNumber,
        "VanName": vanName,
        "TransactionRemarks1": transactionRemarks1,
        "TransactionRemarks2": transactionRemarks2,
        "AccountTypeNumber": accountTypeNumber,
        "CustomerName": customerName,
        "ContactPerson": contactPerson,
        "CustomerSeriesNumber": customerSeriesNumber,
        "CustomerCode": customerCode,
        "CustomerAddress": customerAddress,
        "CustomerPlace": customerPlace,
        "CustomerPost": customerPost,
        "CustomerDistrict": customerDistrict,
        "DeliveryAddress": deliveryAddress,
        "Email": email,
        "PopupMessage": popupMessage,
        "CustomerPhone": customerPhone,
        "AgentCode": agentCode,
        "AgentName": agentName,
        "SalesManName": salesManName,
        "SalesManCode": salesManCode,
        "StockPointNameFrom": stockPointNameFrom,
        "StockPointNameTo": stockPointNameTo,
        "StockPointNumberTo": stockPointNumberTo,
        "StockPointNumberFrom": stockPointNumberFrom,
        "StockPointName": stockPointName,
        "MemberName": memberName,
        "MemberCode": memberCode,
        "MemberMobileNo": memberMobileNo,
        "SMSMobileNo": smsMobileNo,
        "AreaName": areaName,
        "AreaCode": areaCode,
        "UserNameOpened": userNameOpened,
        "UserNameSubmit": userNameSubmit,
        "VehicleNumber": vehicleNumber,
        "CSTNumber": cstNumber,
        "VATNumber": vatNumber,
        "GSTNumber": gstNumber,
        "PANNumber": panNumber,
        "StateNumber": stateNumber,
        "StateCode": stateCode,
        "StateName": stateName,
        "LicenseNumber": licenseNumber,
        "DocumentNumber": documentNumber,
        "DocumentDate": documentDate,
        "DocumentDatePR": documentDatePr,
        "DocumentAmount": documentAmount,
        "DocumentAmountDiff": documentAmountDiff,
        "UserNumberModified": userNumberModified,
        "CounterModified": counterModified,
        "ModifiedDate": modifiedDate,
        "UserNumberOpened": userNumberOpened,
        "UserNumberSubmit": userNumberSubmit,
        "SubmitDate": submitDate,
        "SubmitTypeNumber": submitTypeNumber,
        "UserSubmitRemarks": userSubmitRemarks,
        "UserHierarchy": userHierarchy,
        "IsCancel": isCancel,
        "BillEdited": billEdited,
        "UpdateMaster": updateMaster,
        "UpdateItemMasterGST": updateItemMasterGst,
        "TransactionNumberImport": transactionNumberImport,
        "TransactionDateImport": transactionDateImport,
        "TransAgentRate": transAgentRate,
        "TransAgentAmount": transAgentAmount,
        "TransCommRate": transCommRate,
        "TransCommAmount": transCommAmount,
        "TransFreightAmount": transFreightAmount,
        "TransSalesTaxRate": transSalesTaxRate,
        "TransSalesTaxAmount": transSalesTaxAmount,
        "TransCessRate": transCessRate,
        "TransCessAmount": transCessAmount,
        "TransOtherExpense": transOtherExpense,
        "AgentRate": agentRate,
        "AgentAmount": agentAmount,
        "CommRate": commRate,
        "CommAmount": commAmount,
        "TransCostAmount": transCostAmount,
        "TransSplDiscRate": transSplDiscRate,
        "TransSplDiscAmount": transSplDiscAmount,
        "TransDisplayAmount": transDisplayAmount,
        "ItemTotalAmount": itemTotalAmount,
        "TransactionCost": transactionCost,
        "TransactionPostingAmount": transactionPostingAmount,
        "ItemTotalGrossAmount": itemTotalGrossAmount,
        "ItemTotalDiscount": itemTotalDiscount,
        "ItemTotalExtraDiscount": itemTotalExtraDiscount,
        "ItemTotalNetAmount": itemTotalNetAmount,
        "ItemTotalTaxAmount": itemTotalTaxAmount,
        "TransExtraTotal": transExtraTotal,
        "IncludeTaxInPrice": includeTaxInPrice,
        "CurrencySymbol": currencySymbol,
        "LuxuryItemGroupNumber": luxuryItemGroupNumber,
        "LuxuryGSTRate": luxuryGstRate,
        "LuxuryPriceTypeNumber": luxuryPriceTypeNumber,
        "IsLuxury": isLuxury,
        "TenderCash": tenderCash,
        "AccountTypeNumberPayment": accountTypeNumberPayment,
        "AccHeadNumberPayment": accHeadNumberPayment,
        "AccHeadNumberAdvance": accHeadNumberAdvance,
        "AdvanceAmount": advanceAmount,
        "BalanceCash": balanceCash,
        "IsLocked": isLocked,
        "CurrencyDecimals": currencyDecimals,
        "AllowManualBillNo": allowManualBillNo,
        "ItemQuantityTotal": itemQuantityTotal,
        "ItemSaleQuantityTotal": itemSaleQuantityTotal,
        "DiscountQuantityTotal": discountQuantityTotal,
        "ItemTotalQuantityTotal": itemTotalQuantityTotal,
        "ItemNetUnitPriceTotal": itemNetUnitPriceTotal,
        "SpecialDiscAmountTotal": specialDiscAmountTotal,
        "ItemTaxAmountTotal": itemTaxAmountTotal,
        "ItemGSTAmountTotal": itemGstAmountTotal,
        "ItemSGSTAmountTotal": itemSgstAmountTotal,
        "ItemCGSTAmountTotal": itemCgstAmountTotal,
        "ItemIGSTAmountTotal": itemIgstAmountTotal,
        "ItemGSTCessAmountTotal": itemGstCessAmountTotal,
        "ItemCessAmountTotal": itemCessAmountTotal,
        "TransDiscAmountTotal": transDiscAmountTotal,
        "ItemCostPriceTotal": itemCostPriceTotal,
        "ItemAgentAmountTotal": itemAgentAmountTotal,
        "ItemAgentAmountAfterNetAmountTotal":
            itemAgentAmountAfterNetAmountTotal,
        "MarginRateTotal": marginRateTotal,
        "ItemCommissionAmountTotal": itemCommissionAmountTotal,
        "ItemOtherExpenseAmountTotal": itemOtherExpenseAmountTotal,
        "ItemExpenseAmountTotal": itemExpenseAmountTotal,
        "PackingExpenseTotal": packingExpenseTotal,
        "ItemExtraDiscountAmountTotal": itemExtraDiscountAmountTotal,
        "ItemSalesPriceProfitTotal": itemSalesPriceProfitTotal,
        "ItemSalesPrice1ProfitTotal": itemSalesPrice1ProfitTotal,
        "ItemSalesPrice2ProfitTotal": itemSalesPrice2ProfitTotal,
        "ItemSalesPrice3ProfitTotal": itemSalesPrice3ProfitTotal,
        "ItemSalesPrice4ProfitTotal": itemSalesPrice4ProfitTotal,
        "ItemSalesPrice5ProfitTotal": itemSalesPrice5ProfitTotal,
        "ItemHandlingChargesTotal": itemHandlingChargesTotal,
        "SchemeNumber": schemeNumber,
        "IssueNumber": issueNumber,
        "ConsumptionAmount": consumptionAmount,
        "SeriesTypeName": seriesTypeName,
        "SchemeItemAmountTotal": schemeItemAmountTotal,
        "TransSchemeDiscountString": transSchemeDiscountString,
        "TransSchemeDiscount": transSchemeDiscount,
        "CostCentreNumber": costCentreNumber,
        "TransactionDueDate": transactionDueDate,
        "TransactionDueDateString": transactionDueDateString,
        "PrintCopyName": printCopyName,
        "PackingSlipNo": packingSlipNo,
        "GroupTypeNumber1": groupTypeNumber1,
        "GroupTypeNumber2": groupTypeNumber2,
        "GroupTypeNumber3": groupTypeNumber3,
        "ItemGroupNumber1": itemGroupNumber1,
        "ItemGroupNumber2": itemGroupNumber2,
        "ItemGroupNumber3": itemGroupNumber3,
        "ZeroQuantityItem": zeroQuantityItem,
        "CashForward": cashForward,
        "PreviousBillCashForward": previousBillCashForward,
        "UserName": userName,
        "JollySilksPoints": jollySilksPoints,
        "JollySilksAmount": jollySilksAmount,
        "JoyMartPoints": joyMartPoints,
        "JoyMartAmount": joyMartAmount,
        "SeriesName": seriesName,
        "CurrencyNumber": currencyNumber,
        "CurrencyRate": currencyRate,
        "AccHeadName": accHeadName,
        "AccHeadStatus": accHeadStatus,
        "MemPassword": memPassword,
        "DistrictNumber": districtNumber,
        "DeliveryDate": deliveryDate,
        "TransPrintStatus": transPrintStatus,
        "CompanyWiseMemberPoint": companyWiseMemberPoint,
        "ItemUnitPriceCurrency": itemUnitPriceCurrency,
        "TransCostAmount1": transCostAmount1,
        "TransCostAmount1string": transCostAmount1String,
        "TransCostAmount2": transCostAmount2,
        "TransCostAmount2string": transCostAmount2String,
        "TransCostAmount3": transCostAmount3,
        "TransCostAmount3string": transCostAmount3String,
        "ItemPrefix": itemPrefix,
        "ItemGroupNumber": itemGroupNumber,
        "ItemGroup": itemGroup,
        "CategoryGroup": categoryGroup,
        "SizeGroup": sizeGroup,
        "ColorGroup": colorGroup,
        "CurrencyTotal": currencyTotal,
        "CalculationOnSqrMeter": calculationOnSqrMeter,
        "NetAmountTotal": netAmountTotal,
        "GSTTotal": gstTotal,
        "IGSTTotal": igstTotal,
        "CGSTTotal": cgstTotal,
        "SGSTTotal": sgstTotal,
        "TotalItemHandlingCharge": totalItemHandlingCharge,
        "SchemDisAfterTax": schemDisAfterTax,
        "SchemDisBeforeTax": schemDisBeforeTax,
        "TransFreightServiceItemNumber": transFreightServiceItemNumber,
        "TransFreightServiceItemCode": transFreightServiceItemCode,
        "TransFreightServiceItemName": transFreightServiceItemName,
        "TransFreightAmountTaxable": transFreightAmountTaxable,
        "ServiceItemGSTRate": serviceItemGstRate,
        "ServiceItemNumber2": serviceItemNumber2,
        "ServiceItemCode2": serviceItemCode2,
        "ServiceItemName2": serviceItemName2,
        "TransExpensesAmountTaxable": transExpensesAmountTaxable,
        "ServiceItemGSTRate2": serviceItemGstRate2,
        "ServiceItemNumber3": serviceItemNumber3,
        "ServiceItemCode3": serviceItemCode3,
        "ServiceItemName3": serviceItemName3,
        "TransDisplayAmountTaxable": transDisplayAmountTaxable,
        "ServiceItemGSTRate3": serviceItemGstRate3,
        "TransFreightCGSTRate": transFreightCgstRate,
        "TransFreightCGSTAmount": transFreightCgstAmount,
        "TransFreightSGSTRate": transFreightSgstRate,
        "TransFreightSGSTAmount": transFreightSgstAmount,
        "TransFreightIGSTRate": transFreightIgstRate,
        "TransFreightIGSTAmount": transFreightIgstAmount,
        "TransExpensesCGSTRate": transExpensesCgstRate,
        "TransExpensesCGSTAmount": transExpensesCgstAmount,
        "TransExpensesSGSTRate": transExpensesSgstRate,
        "TransExpensesSGSTAmount": transExpensesSgstAmount,
        "TransExpensesIGSTRate": transExpensesIgstRate,
        "TransExpensesIGSTAmount": transExpensesIgstAmount,
        "TransDisplayCGSTRate": transDisplayCgstRate,
        "TransDisplayCGSTAmount": transDisplayCgstAmount,
        "TransDisplaySGSTRate": transDisplaySgstRate,
        "TransDisplaySGSTAmount": transDisplaySgstAmount,
        "TransDisplayIGSTRate": transDisplayIgstRate,
        "TransDisplayIGSTAmount": transDisplayIgstAmount,
        "Is90DaysBefore": is90DaysBefore,
        "ProfitRate": profitRate,
        "ProfitAmount": profitAmount,
        "TransItemCostPriceTotal": transItemCostPriceTotal,
        "GSTEnabled": gstEnabled,
        "GSTCategory": gstCategory,
        "CurrencyName": currencyName,
        "TransCurrencyRate": transCurrencyRate,
        "TransCurrencyAmount": transCurrencyAmount,
        "blnCalcSalesPrice": blnCalcSalesPrice,
        "SupplierNumber": supplierNumber,
        "SupplierCode": supplierCode,
        "SupplierName": supplierName,
        "MobileWhatsApp": mobileWhatsApp,
        "CompanyRemarks": companyRemarks,
        "TransFreightGSTRate": transFreightGstRate,
        "TransExpensesGSTRate": transExpensesGstRate,
        "TransExpensesServiceItemNumber": transExpensesServiceItemNumber,
        "TransDisplayGSTRate": transDisplayGstRate,
        "TransDisplayServiceItemNumber": transDisplayServiceItemNumber,
        "DocumentDateString": documentDateString,
        "CustomerCity": customerCity,
        "CustomerLocation": customerLocation,
        "CustomerPincode": customerPincode,
        "BillDiscountCouponRate": billDiscountCouponRate,
        "BillDiscountCouponAmount": billDiscountCouponAmount,
        "DiscCouponDefinitionNumber": discCouponDefinitionNumber,
        "BillDiscountCouponNumber": billDiscountCouponNumber,
        "BillDiscountCouponExpiryDays": billDiscountCouponExpiryDays,
        "DiscountCouponNumber": discountCouponNumber,
        "TCSRate": tcsRate,
        "TCSAmount": tcsAmount,
        "TCSTaxableAmount": tcsTaxableAmount,
        "PaymentlList": paymentlList,
        "DetailList": detailList,
      };
}
